### ISSUE TITLE
Are failed onledger transactions returned as `success` or `error` in `submitTransaction` API?

### ISSUE THREAD

**Issue by dcts** [radixdlt/wallet-sdk#90]
Heres an example of a failed onledger transaction:

**Stokenet**
https://stokenet-dashboard.radixdlt.com/transaction/txid_tdx_2_1yma9m9p05dqjjj7zuhr6yt7enc9vufhnraxskya02erdh2p0crsqpzkjhg/summary

How are transactions like these returned by the [`sendTransaction`](https://github.com/radixdlt/wallet-sdk?tab=readme-ov-file#sendtransaction) API? Are those returned as success or error? In case of error, which errorType?

**Comment by dawidsowardx** [comment]
It's returned as an error. If you're using `sendTransaction` from RDT you won't see `errorType`(for committed transaction) but rather TransactionStatus from the ledger.

**Comment by dcts** [comment]
Is there documentation on `TransactionStatus`? 

You said its not an error type but I saw there is `submittedTransactionHasFailedTransactionStatus`, is that maybe what Im looking for or something else?

**Comment by dawidsowardx** [comment]
Ok, first things first - you should most likely be looking at [RDT repository](https://github.com/radixdlt/radix-dapp-toolkit) rather than this. RDT wraps `wallet-sdk` with some nicer APIs and does **transaction status polling** after it's been submitted.

`TransactionStatus` is defined by gateway-sdk [here](https://github.com/radixdlt/babylon-gateway/blob/d1bb35bec94178b1c851b84c702684546586c33b/sdk/typescript/lib/generated/models/TransactionStatus.ts#L22)

As far as I remember `submittedTransactionHasFailedTransactionStatus` will never occur with recent Radix Wallet versions. It's because Radix Wallet responds to `wallet-sdk` right after transaction has been submitted (Radix Wallet doesn't yet know if transaction has been accepted or rejected). After receiving `transactionIntentHash` we can check the status ourselves - by querying Gateway API.

`sendTransaction` in `wallet-sdk` successful response contains `transactionIntentHash` which is later used by RDT to poll for actual transaction status ([code here](https://github.com/radixdlt/radix-dapp-toolkit/blob/main/src/wallet/wallet-client.ts#L104)).

**Comment by dawidsowardx** [comment]
@dcts coming back to original question because I might have introduced some misunderstanding

Transaction like the one you've linked will be returned as success from wallet-sdk (because it has been submitted) but as an error from radix-dapp-toolkit (after polling we see it's committed failure).

`submittedTransactionHasFailedTransactionStatus` can occur if the wallet fails to submit a transaction (name is misleading)

**Comment by dcts** [comment]
Thanks a lot for detailed explenation!
